envConfig:
  maxCPUCount: 0
  maxMemoryGB: 2
  description: ""
  preCmd:
    - tini
    - java
  args: []
  postCmd:
    - -jar
    - ./app.jar
  nodeSelector: {}
  replicas: 0
  namespace: ""
  overrideNode: false
  gatewayName: gateway-service
  gatewayNodePort: 9000
  hostPort: 31000
  envValues: {}
userGuide: {}
apps:
  - appdeploy:
      appName: gateway-service
      envName: values.yaml
      image: nginx-alpine
      tag: v2
    appconfig:
      maxCPUCount: 2
      maxMemoryGB: 2
      description: 网关服务
      preCmd:
        - tini
        - java
      args: []
      postCmd:
        - -jar
        - ./app.jar
      nodeSelector:
        resources.type/base: "true"
      replicas: 3
      name: gateway-service
      runType: ""
