// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	AppConfig *appConfig
	AppDeploy *appDeploy
	EnvConfig *envConfig
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AppConfig = &Q.AppConfig
	AppDeploy = &Q.AppDeploy
	EnvConfig = &Q.EnvConfig
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		AppConfig: newAppConfig(db, opts...),
		AppDeploy: newAppDeploy(db, opts...),
		EnvConfig: newEnvConfig(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AppConfig appConfig
	AppDeploy appDeploy
	EnvConfig envConfig
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		AppConfig: q.AppConfig.clone(db),
		AppDeploy: q.AppDeploy.clone(db),
		EnvConfig: q.EnvConfig.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		AppConfig: q.AppConfig.replaceDB(db),
		AppDeploy: q.AppDeploy.replaceDB(db),
		EnvConfig: q.EnvConfig.replaceDB(db),
	}
}

type queryCtx struct {
	AppConfig IAppConfigDo
	AppDeploy IAppDeployDo
	EnvConfig IEnvConfigDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AppConfig: q.AppConfig.WithContext(ctx),
		AppDeploy: q.AppDeploy.WithContext(ctx),
		EnvConfig: q.EnvConfig.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
