global:
  namespace: dev-environment

envConfig:
  maxCpuCount: 2
  maxMemoryGB: 2
  preCmd:
    - tini
    - java
  postCmd:
    - -jar
    - ./app.jar
  overrideNode: false
  nodeSelector: {}
  gatewayName: gateway-service
  gatewayNodePort: 9000
  hostPort: 31000
  replicas: 0

apps:
  - name: demo-service
    image: adf
    tag: v1
    maxCpuCount: 2
    maxMemoryGB: 2
    javaArgs: []
    nodeSelector: {}
    replicas: 1
